version: "3.9"
services:
  app:
    image: edemreshidov/devops-for-programmers-project-lvl1:latest
    build:
      context: .
      dockerfile: Dockerfile.production
    command: npm test
    volumes:
      - ./app:/app
