name: push

on:
  push:
    branches:
      - main
env:
  IMAGE_NAME: edemreshidov/devops-for-programmers-project-lvl1:latest

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      -
        name: Checkout
        uses: actions/checkout@v3
      -
        name: Install deps
        uses: actions/setup-node@v3
        with:
          node-version: 14.18.1
          cache: 'npm'
      -
        name: Run tests
        run: |
          make ci
      -
        name: Set up QEMU
        uses: docker/setup-qemu-action@v2
      -
        name: Set up Docker Buildx
        uses: docker/setup-buildx-action@v2
      -
        name: Login to Docker Hub
        uses: docker/login-action@v2
        with:
          username: ${{ secrets.DOCKERHUB_USERNAME }}
          password: ${{ secrets.DOCKERHUB_TOKEN }}
      -
        name: Build and export to Docker
        uses: docker/build-push-action@v4
        with:
          context: .
          file: Dockerfile.production
          tags: ${{ env.IMAGE_NAME }}
          push: true
          cache-from: type=registry,ref=${{ env.IMAGE_NAME }}
          cache-to: type=inline                    
      
